{"name": "test_datetime_validation", "status": "broken", "statusDetails": {"message": "AttributeError: module 'datetime' has no attribute 'strptime'", "trace": "auth_header = {'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJXNTRsQzhsei1Yek9tVDhOMDFCTXdXLXlYbTFodGpH...tyObUB-fZV_k77IjH1Gw0skC8ZhErdtdpU46sT7qXEIR5qRTNZVBg-wZM_Vml2jfhf9eGexGPwlglYfxqHpkgSq-rFsQD8s1H4t6jfdSvAtzO-sMijQyA'}\n\n    def test_datetime_validation(auth_header):\n    \n        \"\"\"Proving the datetime for `aotRegistratiedatum`\"\"\"\n    \n        payload = {\"id\": '2022-01-01.0363200000205917.3'}\n        response = requests.get(dataconstantstandvastgoed.dataset_url, params=payload, headers=auth_header)\n        content =response.json()\n        records = content[\"_embedded\"][\"gebouwen\"]\n        aotRegistratiedatum = records[0][\"aotRegistratiedatum\"]\n        # initializing format\n        format = \"%Y-%m-%dT%H:%M:%S\"\n        # checking if format matches the date\n        res = True\n    \n        # using try-except to check for truth value\n        try:\n>           res = bool(datetime.strptime(aotRegistratiedatum, format))\nE           AttributeError: module 'datetime' has no attribute 'strptime'\n\ne2etest/test_datasetstandvastgoed.py:62: AttributeError"}, "description": "Proving the datetime for `aotRegistratiedatum`", "start": 1646909713182, "stop": 1646909713370, "uuid": "20fd6c89-a549-49dd-ba6a-7c53e10bee2c", "historyId": "9aa2535396bb8458f0c3ec4644b2391d", "testCaseId": "1ecbf52995299e6bac70a55377dd51e3", "fullName": "e2etest.test_datasetstandvastgoed#test_datetime_validation", "labels": [{"name": "parentSuite", "value": "e2etest"}, {"name": "suite", "value": "test_datasetstandvastgoed"}, {"name": "host", "value": "Jayashrees-MacBook-Pro.local"}, {"name": "thread", "value": "64535-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "e2etest.test_datasetstandvastgoed"}]}